# data-wrangling
Pythonで始めるdata-wrangling

なぜか、pushできなくなったから、新しいリモートリポジトリ作成。
この問題はあとで解決することにした。



git push -f origin master 
で強制的にpush 

まだよくわからんけど、とりあえず問題は解決？笑
